steps:
  # 1. Tests
  - name: golang:1.22
    entrypoint: bash
    args:
      - -c
      - |
        go test ./...

  # 2. Build l’image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-t',
        'europe-west9-docker.pkg.dev/$PROJECT_ID/quelpoke/webapp:$SHORT_SHA',
        '.'
      ]

  # 3. Push de l’image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west9-docker.pkg.dev/$PROJECT_ID/quelpoke/webapp:$SHORT_SHA'
      ]

  # 4. Déploiement Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'quelpoke',
        '--image=europe-west9-docker.pkg.dev/$PROJECT_ID/quelpoke/webapp:$SHORT_SHA',
        '--region=europe-west9',
        '--platform=managed',
        '--allow-unauthenticated'
      ]

images:
  - europe-west9-docker.pkg.dev/$PROJECT_ID/quelpoke/webapp:$SHORT_SHA
